In [31]:
# Parse mat (Matlab workspace) file
import os
os.environ["PYDEVD_WARN_SLOW_RESOLVE_TIMEOUT"] = "11.0"

import scipy.io
import numpy as np

# Load the .mat file
mat_data = scipy.io.loadmat('../../../Projects/NeuralMorphology/Matlab/SkeletonAnalysis.mat')

# Print the keys to see what variables are stored
print(mat_data.keys())

# Access a specific variable (e.g., 'data')
dendrite = mat_data['Skeletonized']
#print(dendrite[0])

print(type(dendrite))      # Should be <class 'numpy.ndarray'>
print(dendrite.shape)      # Shape of the array
print(dendrite.dtype)      # Data type of elements

Neuron = dendrite[0, 0]
print(type(Neuron))      # Should be <class 'numpy.ndarray'>
print(Neuron.shape)      # Shape of the array
print(Neuron.dtype)

if dendrite.dtype.names:  # Check if it's a structured array
    for name in dendrite.dtype.names:
        print(f"Field '{name}'\n")  # Access fields

branches = [dendrite[i, 0]['Branch'] for i in range(dendrite.shape[0])]
print(branches[0].shape) 
print(branches[0].dtype)

print(branches[0]['Subtree'].shape) 
print(branches[0]['Subtree'].dtype)

print(branches[0]['Subtree'][0, 0].shape)
print(branches[0]['Subtree'][0, 0].dtype)
print(branches[0]['Subtree'][0, 0]['NTippoints'])
print(branches[0]['Subtree'][0, 0]['NTippoints'][0,0].item())

print(branches[0]['Subtree'][0, 0]['NBranches'])

print(dendrite[0]['Branch'][0]['Subtree'][0,0]['NBranches'])

print(dendrite[0]['Neuron'][0]['info'][0,0]['ColorType'][0,0].item())

print(branches[0]['Subtree'][0, 0]['skel'][0,0]['level'].shape, branches[0]['Subtree'][0, 0]['skel'][0,0]['level'].dtype)

dict_keys(['__header__', '__version__', '__globals__', 'Skeletonized'])
<class 'numpy.ndarray'>
(12, 1)
[('Neuron', 'O'), ('Branch', 'O')]
<class 'numpy.void'>
()
[('Neuron', 'O'), ('Branch', 'O')]
Field 'Neuron'

Field 'Branch'

(1, 1)
[('Subtree', 'O')]
(1, 1)
object
(1, 3)
[('skel', 'O'), ('TotalLength', 'O'), ('NBranches', 'O'), ('BranchpointPositions', 'O'), ('NBranchpoints', 'O'), ('NTippoints', 'O'), ('Level', 'O'), ('Subtree', 'O')]
[[array([[53]], dtype=uint8) array([[145]], dtype=uint8)
  array([[114]], dtype=uint8)]]
53
[[array([[125]], dtype=uint8) array([[387]], dtype=uint16)
  array([[295]], dtype=uint16)]]
[[array([[125]], dtype=uint8) array([[387]], dtype=uint16)
  array([[295]], dtype=uint16)]]
grayscale
(1, 125) object
